# Generated by Django 5.2.7 on 2025-10-30 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('crop_name', models.CharField(max_length=100)),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('irrigation_count', models.PositiveIntegerField(default=0)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('ambient_temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('weather_info', models.JSONField(blank=True, help_text='Datos de clima: lluvia, temperatura, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
